version: '3.8'
services:
  ftp-server:
    container_name: my-ftp-server
    image: garethflowers/ftp-server
    environment:
      - FTP_PASS=FTP_PASS
      - FTP_USER=FTP_USER
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'